version: '3.8'

services:
  postgres-db:
    container_name: Bluelock
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_Bluelock_data:/var/lib/postgresql/data

volumes:
  postgres_Bluelock_data: