version: '3.8'

services:
  postgres-db:
    container_name: Hotaru
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_hotaru_data:/var/lib/postgresql/data

volumes:
  postgres_hotaru_data: